### ISSUE TITLE
LICENSE file includes Apache license template, rather than filled-out license

### ISSUE THREAD

**Issue by kevinushey** [samthor/fast-text-encoding#10]
A minor note, but it looks like the LICENSE file includes the template but doesn't fill it out:

https://github.com/samthor/fast-text-encoding/blob/0423145077f8fbbef5ae7c346ccf44da4d2581da/LICENSE#L189

**Comment by samthor** [comment]
AFAIK that is literally intended to be the template. The copyright at the top of "text.js" is the implemented version.

**Comment by kevinushey** [comment]
Ah, got it. Thanks for the clarification and sorry for the noise!
