### ISSUE TITLE
Null padded string length not preserved

### ISSUE THREAD

**Issue by kitsonk** [samthor/fast-text-encoding#2]
When dealing with certain buffers from other systems, the string is padded with `null`.  The native implementations preserve this and simply copy the `null`s over to the string, ensuring that the length is correct.

This part of the decode does not allow that to happen in `fast-text-encoding`:

https://github.com/samthor/fast-text-encoding/blob/227d7d28fd3d8021e58bde88158491cdac713921/text.js#L149-L151

**Comment by samthor** [comment]
Thanks, I've resolved this now.
