### ISSUE TITLE
get  [Error: Cannot create URL for blob!]

### ISSUE THREAD

**Issue by Negin-ozn** [samthor/fast-text-encoding#21]
when I use 
`new TextDecoder().decode([72, 101, 108, 108, 111])`
I get  [Error: Cannot create URL for blob!] in react native.
Any solution?

**Comment by Reeywhaar** [comment]
Same. Guess code [here](https://github.com/samthor/fast-text-encoding/blob/19e48946784a8c1b3a6af5283fb46cb9044b368e/text.js#L146) should be moved under `try` block
