### ISSUE TITLE
feat: why not use `codePointAt`?

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [samthor/fast-text-encoding#25]
# Overview

This is a feature request/clarification?

https://github.com/samthor/fast-text-encoding/blob/60d0a6cc787da13c2799c11cae48eba037f74548/src/lowlevel.js#L93-L97

`charCodeAt` gives the UTF-16 codepoints and you need to deal with surrogate pairs.
```
The charCodeAt() method returns an integer between 0 and 65535 representing the UTF-16 code unit at the given index.
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt

For https://en.wikipedia.org/wiki/UTF-8 encoding you just need the Unicode codepoint which is what `codePointAt` provides.
```
The codePointAt() method returns a non-negative integer that is the Unicode code point value at the given position.
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt

Am I missing something? I am not an expert on this topic.

## Code

I wrote an implementation that uses `codePointAt` instead of `charCodeAt`.
https://jsfiddle.net/pzh6ofnj/2/

```js
const f = (s) => new Uint8Array([...s].map(c => c.codePointAt(0)).flatMap(x => {
  if (x < 0x80) {
    // first 128 code points need 1 byte
    return x;
  }
  if (x < 0x800) {
    // next 1920 code points need 2 bytes
    return [((x >>> 6) & 0x1F) | 0xC0, (x & 0x3F) | 0x80];
  }
  if (x < 0x10000) {
    // next 63488 (really only 61440 are in use) code points need 3 bytes
    return [((x >>> 12) & 0x0F) | 0xE0, ((x >>> 6) & 0x3F) | 0x80, (x & 0x3F) | 0x80];
  }
  // rest need 4 bytes
  return [
    ((x >>> 18) & 0x07) | 0xF0,
    ((x >>> 12) & 0x3F) | 0x80,
    ((x >>> 6) & 0x3F) | 0x80,
    (x & 0x3F) | 0x80,
  ];
}));

function main() {
  // const s = 'abcd😊efgh\n012345689\t€\r🧑🏽‍🍳helloworld!';
  const s = '$£Иह€한𐍈';

  console.log(s);
  const arr = f(s);
  console.log(Array.from(arr).map(x => x.toString(16)));

  // test against TextEncoder
  {
    const expected = new TextEncoder().encode(s);
    console.log(Array.from(expected).map(x => x.toString(16)));
    const actual = Array.from(arr);
    if (Array.from(expected).some((x, i) => x !== actual[i])) {
      throw new Error('the encoded bytes do not match');
    }
  }
  // test against TextDecoder
  {
    const actual = new TextDecoder().decode(arr);
    console.log(actual);
    if (actual !== s) {
      throw new Error(`the decoded string does not match the original: ${actual}`);
    }

  }
}

main();
```

**Comment by samthor** [comment]
The `codePointAt` method has similar levels of support to `TextEncoder` and `TextDecoder`—see MDN—so it doesn't make sense to use it to implement a polyfill. You'd be polyfilling that too.

JS has come a long way. Honestly this polyfill _shouldn't be used_ any more by most people, because [96%+](https://caniuse.com/textencoder) of browsers don't need it. That's why I publish an "@​empty" version in case you get this package transitively.
