### ISSUE TITLE
Probably not needed anymore?

### ISSUE THREAD

**Issue by jimmywarting** [samthor/fast-text-encoding#26]
time for deprecation
and archiving the Github repo?

all green env. have text encoder/decoder nowdays

**Comment by daniel-xyz** [comment]
Unfortunately it's still needed for React Native

**Comment by samthor** [comment]
If you don't want this as a transitive dependency, pin the `@​empty` version in your NPM or whatever package file.

I'm unfortunately not responsible for folks who include this.
