### ISSUE TITLE
IE11 doesn't work

### ISSUE THREAD

**Issue by dmitryy** [samthor/fast-text-encoding#3]
Object doesn't support property or method 'slice', when trying to encode something in IE11
`(new TextEncoder()).encode('sample string')`

**Comment by LeParadoxHD** [comment]
> Object doesn't support property or method 'slice', when trying to encode something in IE11
> `(new TextEncoder()).encode('sample string')`

Same here

**Comment by elion** [comment]
Any news on this?

**Comment by LeParadoxHD** [comment]
> Any news on this?

Noup :(

**Comment by elion** [comment]
I managed to get it working with this [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice#Polyfill).

**Comment by LeParadoxHD** [comment]
> I managed to get it working with this [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice#Polyfill).

Hero!

**Comment by ktsangop** [comment]
> I managed to get it working with this [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice#Polyfill).

Thank you for that!
Would be nice to add it to `fast-text-encoding` polyfill since it uses `Uint8Array`..

**Comment by samthor** [comment]
This will be fixed in the next release (hopefully today).
