### ISSUE TITLE
utfLabel argument does not support "utf8"

### ISSUE THREAD

**Issue by mfellner** [samthor/fast-text-encoding#4]
FastTextDecoder and FastTextEncoder should also support a `utfLabel` argument with the value "utf8". Currently the constructors throw an error if the argument is not exactly equal to "utf-8" (https://github.com/samthor/fast-text-encoding/blob/master/text.js#L36).

According to https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/TextDecoder, both "utf8" and "utf-8" are acceptable values for `utfLabel`

### How to reproduce

Some libraries, e.g. https://github.com/kripken/sql.js, pass the value "utf8" to the TextDecoder (or Encoder) constructor.

I found this issue by accident, since our project uses the following libraries (amongst others):

* https://github.com/googleapis/google-auth-library-nodejs (includes fast-text-encoding)
  * https://github.com/samthor/fast-text-encoding
* https://github.com/typeorm/typeorm (uses sql.js)
  * https://github.com/kripken/sql.js

TypeORM attempts to require sql.js, which then fails with this error:
```
RangeError: Failed to construct 'TextDecoder': The encoding label provided ('utf8') is invalid.
```
Apparently by some strange coincident this issue has not occurred earlier in our codebase. Perhaps it has something to do with the order in which some transitive dependencies are required.

**Comment by mfellner** [comment]
By the way, for anyone running into this issue because of google-auth-library, the issue should be fixed on their side in an upcoming version: https://github.com/googleapis/google-auth-library-nodejs/issues/626

**Comment by samthor** [comment]
Thanks, I've fixed this and will release today.
